// This file is part of Bifrost.

// Copyright (C) 2019-2022 Liebi Technologies (UK) Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for bifrost_cross_in_out
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `bifrost-jenkins`, CPU: `Intel(R) Xeon(R) CPU E5-26xx v4`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("bifrost-kusama-local"), DB CACHE: 1024

// Executed Command:
// target/release/bifrost
// benchmark
// pallet
// --chain=bifrost-kusama-local
// --steps=50
// --repeat=20
// --pallet=bifrost_cross_in_out
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/cross-in-out/src/weights.rs
// --template=./frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for bifrost_cross_in_out.
pub trait WeightInfo {
	fn register_currency_for_cross_in_out() -> Weight;
	fn deregister_currency_for_cross_in_out() -> Weight;
	fn set_crossing_minimum_amount() -> Weight;
	fn add_to_issue_whitelist() -> Weight;
	fn remove_from_issue_whitelist() -> Weight;
	fn add_to_register_whitelist() -> Weight;
	fn remove_from_register_whitelist() -> Weight;
	fn cross_in() -> Weight;
	fn register_linked_account() -> Weight;
	fn cross_out() -> Weight;
	fn change_outer_linked_account() -> Weight;
}

/// Weights for bifrost_cross_in_out using the Bifrost node and recommended hardware.
pub struct BifrostWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for BifrostWeight<T> {
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:1)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	fn register_currency_for_cross_in_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `2517`
		// Minimum execution time: 27_005_000 picoseconds.
		Weight::from_parts(28_306_000, 2517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:1)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	fn deregister_currency_for_cross_in_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `2560`
		// Minimum execution time: 33_028_000 picoseconds.
		Weight::from_parts(33_854_000, 2560)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut CrossingMinimumAmount (r:0 w:1)
	/// Proof Skipped: CrossInOut CrossingMinimumAmount (max_values: None, max_size: None, mode: Measured)
	fn set_crossing_minimum_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_549_000 picoseconds.
		Weight::from_parts(23_959_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut IssueWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut IssueWhiteList (max_values: None, max_size: None, mode: Measured)
	fn add_to_issue_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `2517`
		// Minimum execution time: 37_476_000 picoseconds.
		Weight::from_parts(38_673_000, 2517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut IssueWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut IssueWhiteList (max_values: None, max_size: None, mode: Measured)
	fn remove_from_issue_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `2627`
		// Minimum execution time: 35_871_000 picoseconds.
		Weight::from_parts(36_621_000, 2627)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut RegisterWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut RegisterWhiteList (max_values: None, max_size: None, mode: Measured)
	fn add_to_register_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `2517`
		// Minimum execution time: 37_414_000 picoseconds.
		Weight::from_parts(38_725_000, 2517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut RegisterWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut RegisterWhiteList (max_values: None, max_size: None, mode: Measured)
	fn remove_from_register_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `2627`
		// Minimum execution time: 31_095_000 picoseconds.
		Weight::from_parts(32_027_000, 2627)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut CrossingMinimumAmount (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossingMinimumAmount (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut IssueWhiteList (r:1 w:0)
	/// Proof Skipped: CrossInOut IssueWhiteList (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(38), added: 2513, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn cross_in() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1685`
		//  Estimated: `24349`
		// Minimum execution time: 128_596_000 picoseconds.
		Weight::from_parts(130_717_000, 24349)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: CrossInOut RegisterWhiteList (r:1 w:0)
	/// Proof Skipped: CrossInOut RegisterWhiteList (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut AccountToOuterMultilocation (r:1 w:1)
	/// Proof Skipped: CrossInOut AccountToOuterMultilocation (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut OuterMultilocationToAccount (r:0 w:1)
	/// Proof Skipped: CrossInOut OuterMultilocationToAccount (max_values: None, max_size: None, mode: Measured)
	fn register_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `8189`
		// Minimum execution time: 51_323_000 picoseconds.
		Weight::from_parts(52_251_000, 8189)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut CrossingMinimumAmount (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossingMinimumAmount (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	/// Storage: CrossInOut AccountToOuterMultilocation (r:1 w:0)
	/// Proof Skipped: CrossInOut AccountToOuterMultilocation (max_values: None, max_size: None, mode: Measured)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(38), added: 2513, mode: MaxEncodedLen)
	fn cross_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1739`
		//  Estimated: `21962`
		// Minimum execution time: 108_862_000 picoseconds.
		Weight::from_parts(109_900_000, 21962)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut AccountToOuterMultilocation (r:1 w:1)
	/// Proof Skipped: CrossInOut AccountToOuterMultilocation (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut OuterMultilocationToAccount (r:0 w:1)
	/// Proof Skipped: CrossInOut OuterMultilocationToAccount (max_values: None, max_size: None, mode: Measured)
	fn change_outer_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `309`
		//  Estimated: `5877`
		// Minimum execution time: 51_122_000 picoseconds.
		Weight::from_parts(52_439_000, 5877)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:1)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	fn register_currency_for_cross_in_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `2517`
		// Minimum execution time: 27_005_000 picoseconds.
		Weight::from_parts(28_306_000, 2517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:1)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	fn deregister_currency_for_cross_in_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `2560`
		// Minimum execution time: 33_028_000 picoseconds.
		Weight::from_parts(33_854_000, 2560)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut CrossingMinimumAmount (r:0 w:1)
	/// Proof Skipped: CrossInOut CrossingMinimumAmount (max_values: None, max_size: None, mode: Measured)
	fn set_crossing_minimum_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 23_549_000 picoseconds.
		Weight::from_parts(23_959_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut IssueWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut IssueWhiteList (max_values: None, max_size: None, mode: Measured)
	fn add_to_issue_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `2517`
		// Minimum execution time: 37_476_000 picoseconds.
		Weight::from_parts(38_673_000, 2517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut IssueWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut IssueWhiteList (max_values: None, max_size: None, mode: Measured)
	fn remove_from_issue_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `2627`
		// Minimum execution time: 35_871_000 picoseconds.
		Weight::from_parts(36_621_000, 2627)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut RegisterWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut RegisterWhiteList (max_values: None, max_size: None, mode: Measured)
	fn add_to_register_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `2517`
		// Minimum execution time: 37_414_000 picoseconds.
		Weight::from_parts(38_725_000, 2517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut RegisterWhiteList (r:1 w:1)
	/// Proof Skipped: CrossInOut RegisterWhiteList (max_values: None, max_size: None, mode: Measured)
	fn remove_from_register_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `152`
		//  Estimated: `2627`
		// Minimum execution time: 31_095_000 picoseconds.
		Weight::from_parts(32_027_000, 2627)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut CrossingMinimumAmount (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossingMinimumAmount (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut IssueWhiteList (r:1 w:0)
	/// Proof Skipped: CrossInOut IssueWhiteList (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(38), added: 2513, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn cross_in() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1685`
		//  Estimated: `24349`
		// Minimum execution time: 128_596_000 picoseconds.
		Weight::from_parts(130_717_000, 24349)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: CrossInOut RegisterWhiteList (r:1 w:0)
	/// Proof Skipped: CrossInOut RegisterWhiteList (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut AccountToOuterMultilocation (r:1 w:1)
	/// Proof Skipped: CrossInOut AccountToOuterMultilocation (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut OuterMultilocationToAccount (r:0 w:1)
	/// Proof Skipped: CrossInOut OuterMultilocationToAccount (max_values: None, max_size: None, mode: Measured)
	fn register_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `191`
		//  Estimated: `8189`
		// Minimum execution time: 51_323_000 picoseconds.
		Weight::from_parts(52_251_000, 8189)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut CrossingMinimumAmount (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossingMinimumAmount (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	/// Storage: CrossInOut AccountToOuterMultilocation (r:1 w:0)
	/// Proof Skipped: CrossInOut AccountToOuterMultilocation (max_values: None, max_size: None, mode: Measured)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(38), added: 2513, mode: MaxEncodedLen)
	fn cross_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1739`
		//  Estimated: `21962`
		// Minimum execution time: 108_862_000 picoseconds.
		Weight::from_parts(109_900_000, 21962)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: CrossInOut CrossCurrencyRegistry (r:1 w:0)
	/// Proof Skipped: CrossInOut CrossCurrencyRegistry (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut AccountToOuterMultilocation (r:1 w:1)
	/// Proof Skipped: CrossInOut AccountToOuterMultilocation (max_values: None, max_size: None, mode: Measured)
	/// Storage: CrossInOut OuterMultilocationToAccount (r:0 w:1)
	/// Proof Skipped: CrossInOut OuterMultilocationToAccount (max_values: None, max_size: None, mode: Measured)
	fn change_outer_linked_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `309`
		//  Estimated: `5877`
		// Minimum execution time: 51_122_000 picoseconds.
		Weight::from_parts(52_439_000, 5877)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
