
//! Autogenerated weights for bifrost_fee_share
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `VM-16-3-ubuntu`, CPU: `Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("bifrost-kusama-local"), DB CACHE: 1024

// Executed Command:
// target/release/bifrost
// benchmark
// pallet
// --chain=bifrost-kusama-local
// --steps=50
// --repeat=20
// --pallet=bifrost_fee_share
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./runtime/bifrost-kusama/src/weights/bifrost_fee_share.rs
// --template=./frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for bifrost_fee_share.
pub trait WeightInfo {
	fn on_initialize() -> Weight;
	fn create_distribution() -> Weight;
	fn edit_distribution() -> Weight;
	fn set_era_length() -> Weight;
	fn execute_distribute() -> Weight;
	fn delete_distribution() -> Weight;
}

/// Weights for bifrost_fee_share using the Substrate node and recommended hardware.
pub struct BifrostWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for BifrostWeight<T> {
	/// Storage: FeeShare AutoEra (r:1 w:0)
	/// Proof Skipped: FeeShare AutoEra (max_values: Some(1), max_size: None, mode: Measured)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `499`
		// Minimum execution time: 3_477_000 picoseconds.
		Weight::from_parts(3_691_000, 499)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: FeeShare DistributionNextId (r:1 w:1)
	/// Proof Skipped: FeeShare DistributionNextId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: FeeShare DistributionInfos (r:0 w:1)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	fn create_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `503`
		// Minimum execution time: 18_999_000 picoseconds.
		Weight::from_parts(19_586_000, 503)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: FeeShare DistributionInfos (r:1 w:1)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	fn edit_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `171`
		//  Estimated: `2646`
		// Minimum execution time: 19_683_000 picoseconds.
		Weight::from_parts(20_303_000, 2646)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: FeeShare AutoEra (r:0 w:1)
	/// Proof Skipped: FeeShare AutoEra (max_values: Some(1), max_size: None, mode: Measured)
	fn set_era_length() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_554_000 picoseconds.
		Weight::from_parts(12_058_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: FeeShare DistributionInfos (r:1 w:0)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:0)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	fn execute_distribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `13352`
		// Minimum execution time: 40_691_000 picoseconds.
		Weight::from_parts(42_314_000, 13352)
			.saturating_add(T::DbWeight::get().reads(4_u64))
	}
	/// Storage: FeeShare DistributionInfos (r:1 w:1)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:0)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	fn delete_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `13352`
		// Minimum execution time: 41_532_000 picoseconds.
		Weight::from_parts(42_858_000, 13352)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: FeeShare AutoEra (r:1 w:0)
	/// Proof Skipped: FeeShare AutoEra (max_values: Some(1), max_size: None, mode: Measured)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `499`
		// Minimum execution time: 3_477_000 picoseconds.
		Weight::from_parts(3_691_000, 499)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: FeeShare DistributionNextId (r:1 w:1)
	/// Proof Skipped: FeeShare DistributionNextId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: FeeShare DistributionInfos (r:0 w:1)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	fn create_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `503`
		// Minimum execution time: 18_999_000 picoseconds.
		Weight::from_parts(19_586_000, 503)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: FeeShare DistributionInfos (r:1 w:1)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	fn edit_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `171`
		//  Estimated: `2646`
		// Minimum execution time: 19_683_000 picoseconds.
		Weight::from_parts(20_303_000, 2646)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: FeeShare AutoEra (r:0 w:1)
	/// Proof Skipped: FeeShare AutoEra (max_values: Some(1), max_size: None, mode: Measured)
	fn set_era_length() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_554_000 picoseconds.
		Weight::from_parts(12_058_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: FeeShare DistributionInfos (r:1 w:0)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:0)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	fn execute_distribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `13352`
		// Minimum execution time: 40_691_000 picoseconds.
		Weight::from_parts(42_314_000, 13352)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
	}
	/// Storage: FeeShare DistributionInfos (r:1 w:1)
	/// Proof Skipped: FeeShare DistributionInfos (max_values: None, max_size: None, mode: Measured)
	/// Storage: AssetRegistry CurrencyMetadatas (r:1 w:0)
	/// Proof Skipped: AssetRegistry CurrencyMetadatas (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:0)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(118), added: 2593, mode: MaxEncodedLen)
	fn delete_distribution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `13352`
		// Minimum execution time: 41_532_000 picoseconds.
		Weight::from_parts(42_858_000, 13352)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
